bind=XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+ 
bind=XF86MonBrightnessUp,spawn,brightnessctl set +5% 
bind=XF86MonBrightnessDown,spawn,brightnessctl set -5% 
