- name: Install lazyvim 
  ansible.builtin.include_role:
    name: fileinstaller

- ansible.builtin.include_role:
    name: nvim

- ansible.builtin.include_role:
    name: lazygit 

- ansible.builtin.include_role:
    name: ripgrep 

- ansible.builtin.include_role:
    name: fd 

- ansible.builtin.include_role:
    name: treesitter 

- ansible.builtin.include_role:
    name: nodejs 
