bind=SUPER,RETURN,exec,$terminal
bind=SUPER,W,killactive
bind=SUPER_SHIFT,SPACE,togglefloating
bind=SUPER,F,fullscreen,0
bind=SUPER_SHIFT,F,fullscreen,1
bind=SUPER,h,movefocus,l
bind=SUPER,l,movefocus,r
bind=SUPER,k,movefocus,u
bind=SUPER,j,movefocus,d
bind=SUPER_SHIFT,h,movewindow,l
bind=SUPER_SHIFT,l,movewindow,r
bind=SUPER_SHIFT,k,movewindow,u
bind=SUPER_SHIFT,j,movewindow,d
bind=SUPER_SHIFT,e,exec,wlogout -b 2 --protocol layer-shell
